version: '3.8'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-petclinic}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD:-true}
      - MYSQL_USER=${MYSQL_USER:-petclinic}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-petclinic}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-petclinic}
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
